### ISSUE TITLE
Configure coveralls

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#116]
Here's what needs to be pulled over from AAEC:
https://github.com/search?q=repo%3Auclibs%2Faaec%20coveralls&type=code

Once configured, Coveralls should show as another green check on pull request screens.

When it's all done and working, we'll need to make it a **required** check for PRs.

**Comment by haitzlm** [comment]
gotcha!

Lisa Haitz

Developer
UC Libraries
________________________________
From: Glen Horton ***@***.***>
Sent: Thursday, February 22, 2024 3:56:51 PM
To: uclibs/staff-directory-23 ***@***.***>
Cc: Haitz, Lisa (haitzlm) ***@***.***>; Assign ***@***.***>
Subject: [uclibs/staff-directory-23] Configure coveralls (Issue #116)


External Email: Use Caution


Here's what needs to be pulled over from AAEC:
https://github.com/search?q=repo%3Auclibs%2Faaec%20coveralls&type=code

Once configured, Coveralls should show as another green check on pull request screens.

When it's all done and working, we'll need to make it a required check for PRs.
