### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#139]
- [x] Merge remaining PRs
- [x] Final QA check
- [x] Request a security scan on libappstest (wipe, create a scan account)
- [x] Resolve any reported security violations and re-scan
- [x] Submit accessibility scan request
- [x] Create a change request
- [x] Attach passing scan result to change request (get approval)
- [x] Merge qa branch into main branch
- [x] Create/update the changelog 
- [x] Tag the release
- [x] Prep libapps server (directories, Apache, puma service, .env files)
- [x] Deploy code to libapps - test that app runs normally
- [x] Migrate production data to new app
- [x] Post-deploy testing
- [x] Submit 2nd change request
- [x] Coordinate migration with the Business Office
- [x] Redirect old staff directory URL to new location
- [x] Update any existing links to old staff directory URL
- [x] Mark the change request as successful
- [x] Make any needed documentation updates

**Comment by haitzlm** [comment]
Finished!
