### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#186]
1. Update ruby 3.3.1 (resolves vulnerabilities)
1. bundle update
1. yarn upgrade

See https://github.com/uclibs/treatment_database/pull/505/files

Upgrading in Mac environments:

If you're using rbenv:
`CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1) --with-opt-dir=$(brew --prefix openssl@1.1)" rbenv install 3.3.1 && rbenv rehash`
 
If you use rvm:
`rvm reinstall 3.3.1 --with-openssl-dir=`brew --prefix openssl@1.1` --with-opt-dir=`brew --prefix openssl@1.1`

**Comment by haitzlm** [comment]
moved to jira
