### ISSUE TITLE
Use NVM

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#187]
Add a .nvmrc file to the root of the repository with contents `12.22.12`

Update the README instructing users to run `nvm use` to set the appropriate node version.  Add nvm to the list of prerequisites.  

Update Capistrano to "install" and "use" the node version in .nvmrc when deploying to servers (depends on Samantha first configuring nvm on the servers)

Verify everything still works.

**Comment by haitzlm** [comment]
moved to jira
