### ISSUE TITLE
Resolve rubocop offenses and enable CircleCI check

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#82]
There are 7 rubocop offenses on the qa branch that need to be resolved.

Create a new branch.

Run `bundle exec rubocop` to see the offenses.

Run `bundle exec rubocop -a` to automatically fix most of the offenses.  Verify by running rubocop again.

The remaining offense in **db/migrate/20230410182200_add_devise_to_users.rb** can be added to the rubocop.yml excludes.

When rubocop is passing, uncomment the rubocop lines in https://github.com/uclibs/staff-directory-23/blob/qa/.circleci/config.yml#L83-L88 so CircleCI will run a rubocop check for each PR

Commit and push up all those changes to a new PR.

**Comment by haitzlm** [comment]
This should be done with PR#99
