### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#83]
Coveralls is indicating we need a test to cover the `@employees = Employee.all` line in app/controllers/public_controller.rb.

**Comment by haitzlm** [comment]
I think this has been completed with this block the spec test:
    it 'assigns all employees to @employees' do
      FactoryBot.create(:department)
      employee = FactoryBot.create(:employee)
      get :index
      expect(assigns(:employees)).to eq([employee])
    end
