### ISSUE TITLE
Configure mailer

### ISSUE THREAD

**Issue by hortongn** [uclibs/staff-directory-23#89]
Need to ensure sending password reset emails works on the servers.

Copy this line from treatment app to staff directory's config/environments/production.rb:
https://github.com/uclibs/treatment_database/blob/qa/config/environments/production.rb#L69-L72
(change `TREATMENT` to `STADIR`)

Copy these lines treatment app to staff directory's .env.development
https://github.com/uclibs/treatment_database/blob/qa/.env.development#L18-L20
(change `TREATMENT` to `STADIR`)

Create a PR and we will deploy to libappstest and test mail.

**Comment by haitzlm** [comment]
from qa create new mailer branch, tweaks, commit, push then have to update production.

**Comment by haitzlm** [comment]
### **Update:**
In development, the email is generated, such that I can see it in console, and click link it takes me to correct page.
For deploy, getting this error below:

**Attempts to fix:**
- look at aaec and change to their settings. Same error (error #1 below)
- tried treatment settings, same error
- settings now set to mirror treatment for further investigation
- reviewing error. 

**Other Notes:**
-Noted that I dont think AAEC is using Devise, dont know if that matters. 
-When I deploy, I get note: "Missing updated .env.production file in the static directory. The server may not function properly". I traced this to /scripts/start_qp.sh below, (Code Example 1).  Note I have a .env.production.local file, not .env.production. Should this be adjusted?
-CHat GPT suggested the code in Code example #2. 


**Code Example #1**
`if [ ! -f "$(dirname "$(dirname "$(dirname "$( cd "$( dirname "scripts/start_qp.sh" )" >/dev/null 2>&1 && pwd )" )" )" 
)**/static/.env.production**" ]; then
    echo "Missing updated .env.production file in the static directory. The server may not function properly"
else
    cp "$(dirname "$(dirname "$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )" )" )/static/.env.production" 
"$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" )"
fi
`
`
**Error 1**
Error from Deploy
<header>
  <h1>
    OpenSSL::SSL::SSLError
      in Devise::PasswordsController#create
  </h1>
</header>
<div id="container">
    <div class="exception-message">
    <div class="message">SSL_connect returned=1 errno=0 peeraddr=[::1]:25 state=error: certificate verify failed (self signed certificate)</div>
  </div>
  
etc...
`
**Code Example 2**
ChatGPT suggested this code below. I didnt do it, ran out of time!

`Reviewing and configuring Devise and ActionMailer involves editing your Rails application's configuration files to ensure that email settings, including SMTP and SSL/TLS settings, are correctly specified. Here’s how you can do it:
1. ActionMailer Configuration
ActionMailer is responsible for sending emails in a Rails application. You configure it in the environment files located in config/environments/. Depending on your deployment, you might want to set it up in development.rb, production.rb, or both.
Example Configuration in config/environments/production.rb:

ruby
config.action_mailer.default_url_options = { host: 'yourappdomain.com', protocol: 'https' }
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  address:              'smtp.yourmailprovider.com',
  port:                 587,
  domain:               'yourappdomain.com',
  user_name:            'yourusername',
  password:             'yourpassword',
  authentication:       'plain',
  enable_starttls_auto: true,  # This ensures TLS is used
      For SSL (if required by your email provider):
     ssl: true,
     openssl_verify_mode: 'none' # Use only if you need to bypass SSL verification (not recommended for production)
}
`
